## Midterm project - Cyberbullying prediction in Mongolia

This prediction model is based on a synthetic dataset generated based on the UNDP Cyberbullying report "Connecting with care: a survey on cyberbullying among Mongolian youth". The report was released in March 2025 and can be found [here](https://www.undp.org/sites/g/files/zskgke326/files/2025-08/undp_cyberbullying_report_eng_0.pdf).

### 1 Dataset

In [29]:
import pandas as pd
import numpy as np
df_s = pd.read_csv('./data/students_data.csv')

In [30]:
df_s.head()

,id,type,age_group,gender,daily_internet_hours,primary_activity,uses_facebook,num_social_media_accounts,exposed_to_bad_language,learned_bad_words,experienced_cyberbullying,cyberbullying_types,reported_incident,reported_to,mental_health_impact,received_school_education,awareness_level,impact_certainty
0,S0001,Student,13-17,Male,1,Videos,True,4,True,True,True,Defamation; Sexual Harassment,False,NaN,Depression; Anxiety,True,Medium,Unsure
1,S0002,Student,13-17,Male,7,Chatting,True,1,True,True,False,NaN,NaN,NaN,NaN,False,Low,Not Applicable
2,S0003,Student,9-12,Female,0,Social Media,True,3,True,True,False,NaN,NaN,NaN,NaN,True,Medium,Not Applicable
3,S0004,Student,13-17,Female,2,Social Media,False,1,True,False,True,Insults; Defamation,False,NaN,Academic Decline; Anxiety,True,High,Unsure
4,S0005,Student,13-17,Female,6,Chatting,True,1,False,False,False,NaN,NaN,NaN,NaN,False,Low,Not Applicable

In [38]:
# Dataset with data from parents
df_p = pd.read_csv('./data/parents_data.csv')
df_p

,id,type,age_group,internet_control,knows_facebook_age_req,aware_of_child_cyberbullying,concerns_about_device_use,digital_literacy,communicates_about_safety,child_age_group
0,P0001,Parent,35-44,Yes,False,Unsure,NaN,Low,False,13-17
1,P0002,Parent,45-54,Yes,True,Unsure,Insomnia; Academic Performance,Medium,True,9-12
2,P0003,Parent,45-54,Yes,True,No,Insomnia,High,True,13-17
3,P0004,Parent,45-54,Want to but struggle,True,No,Academic Performance; Depression,Low,True,9-12
4,P0005,Parent,25-34,Yes,False,Unsure,Academic Performance,Medium,True,9-12
...,...,...,...,...,...,...,...,...,...,...
1630,P1631,Parent,45-54,Yes,True,No,NaN,High,True,13-17
1631,P1632,Parent,45-54,Yes,False,No,Insomnia,Low,True,9-12
1632,P1633,Parent,45-54,Want to but struggle,True,Unsure,NaN,Low,False,13-17
1633,P1634,Parent,45-54,No,False,No,Academic Performance; Depression,Medium,True,13-17
1634,P1635,Parent,35-44,Yes,True,No,Academic Performance,Medium,True,9-12

### 2 EDA

#### Students

In [32]:
# Checking content of columns for students
for col in df_s.columns:
    print(col)
    print(df_s[col].unique()[:5])
    print(df_s[col].nunique())
    print()

id
['S0001' 'S0002' 'S0003' 'S0004' 'S0005']
3812

type
['Student']
1

age_group
['13-17' '9-12']
2

gender
['Male' 'Female']
2

daily_internet_hours
[1 7 0 2 6]
9

primary_activity
['Videos' 'Chatting' 'Social Media' 'Gaming' 'Studying']
5

uses_facebook
[ True False]
2

num_social_media_accounts
[4 1 3 2]
4

exposed_to_bad_language
[ True False]
2

learned_bad_words
[ True False]
2

experienced_cyberbullying
[ True False]
2

cyberbullying_types
['Defamation; Sexual Harassment' nan 'Insults; Defamation'
 'Insults; Defamation; Exclusion' 'Insults']
30

reported_incident
[False nan True]
2

reported_to
[nan 'Family' 'Friend' 'School Counselor' 'Teacher']
4

mental_health_impact
['Depression; Anxiety' nan 'Academic Decline; Anxiety' 'Insomnia'
 'Depression']
31

received_school_education
[ True False]
2

awareness_level
['Medium' 'Low' 'High']
3

impact_certainty
['Unsure' 'Not Applicable' 'Certain']
3

In [33]:
# Checking content of columns for parents
for col in df_p.columns:
    print(col)
    print(df_p[col].unique()[:5])
    print(df_p[col].nunique())
    print()

id
['P0001' 'P0002' 'P0003' 'P0004' 'P0005']
1635

type
['Parent']
1

age_group
['35-44' '45-54' '25-34' '55+']
4

internet_control
['Yes' 'Want to but struggle' 'No']
3

knows_facebook_age_req
[False  True]
2

aware_of_child_cyberbullying
['Unsure' 'No' 'Yes']
3

concerns_about_device_use
[nan 'Insomnia; Academic Performance' 'Insomnia'
 'Academic Performance; Depression' 'Academic Performance']
30

digital_literacy
['Low' 'Medium' 'High']
3

communicates_about_safety
[False  True]
2

child_age_group
['13-17' '9-12']
2

In [34]:
# Analysing numerical values for students
df_s.describe()

       daily_internet_hours  num_social_media_accounts
count           3812.000000                3812.000000
mean               3.574502                   1.646118
std                2.258884                   1.046744
min                0.000000                   1.000000
25%                2.000000                   1.000000
50%                3.000000                   1.000000
75%                5.000000                   2.000000
max                8.000000                   4.000000

In [35]:
# Analysing numerical values for parents
df_p.describe()

,id,type,age_group,internet_control,knows_facebook_age_req,aware_of_child_cyberbullying,concerns_about_device_use,digital_literacy,communicates_about_safety,child_age_group
count,1635,1635,1635,1635,1635,1635,1159,1635,1635,1635
unique,1635,1,4,3,2,3,30,3,2,2
top,P0001,Parent,35-44,Yes,True,No,Insomnia,Low,True,13-17
freq,1,1635,940,847,1006,989,210,743,869,1108

In [36]:
# Checking missing values for students
df_s.isnull().sum()

id                              0
type                            0
age_group                       0
gender                          0
daily_internet_hours            0
primary_activity                0
uses_facebook                   0
num_social_media_accounts       0
exposed_to_bad_language         0
learned_bad_words               0
experienced_cyberbullying       0
cyberbullying_types          2326
reported_incident            2074
reported_to                  2954
mental_health_impact         2611
received_school_education       0
awareness_level                 0
impact_certainty                0
dtype: int64

In [37]:
# Checking missing values for parents
df_p.isnull().sum()

id                                0
type                              0
age_group                         0
internet_control                  0
knows_facebook_age_req            0
aware_of_child_cyberbullying      0
concerns_about_device_use       476
digital_literacy                  0
communicates_about_safety         0
child_age_group                   0
dtype: int64